name: Master

on:
  push:
    branches:
      - master

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    env:
      working-directory: ./api
      HEROKU_EMAIL: jack.pickard@hotmail.com
      HEROKU_API_NAME: the-hut-bracklesham-api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Build, Push and Release API to Heroku. # Your custom step name
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ env.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_API_NAME }}
          appdir: "./api/"
          usedocker: true
        env:
          HD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HD_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          HD_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          HD_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          HD_AUTH0_DATABASE: ${{ secrets.AUTH0_DATABASE }}
          HD_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          HD_ON_HEROKU: true

  build-app:
    name: Build App
    runs-on: ubuntu-latest
    env:
      working-directory: ./web-app/
      HEROKU_EMAIL: jack.pickard@hotmail.com
      HEROKU_API_NAME: the-hut-bracklesham
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install deps
        working-directory: ${{env.working-directory}}
        run: yarn

      - name: Build the project
        working-directory: ${{env.working-directory}}
        run: yarn build

      - name: Build, Push and Release React App to Heroku. # Your custom step name
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ env.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_API_NAME }}
          buildpack: "https://github.com/heroku/heroku-buildpack-nodejs#latest"
          appdir: "./web-app/"
        env:
          HD_REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
